project_id = "qqafbqcckevvrqnlmyeh"

[functions.youtube-transcript]
verify_jwt = false

[functions.transcript-ai-chat]
verify_jwt = false

[functions.youtube-search]
verify_jwt = false

[functions.ai-search]
verify_jwt = false